# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 1
b = 2
a+b

3

# 3.Define a list and replicate in three different ways.

In [3]:
import copy
l = [1, 2, 3]
l2 = list(l)
l3 = l[:]
l4 = copy.copy(l)
l.append(4)
print(l2, l3, l4)

[1, 2, 3] [1, 2, 3] [1, 2, 3]


# 4.Define two lists and merge them together.

In [5]:
l1 = [1, 2, 5]
l2 = [1, 2, 4, 6]
l3 = [*l1, *l2]
print(l3)


[1, 2, 5, 1, 2, 4, 6]


# 5. Get the last element of the list and print it.

In [6]:
print(l3[-1])

6


# 6.Define a tuple that contains only one element.

In [9]:
t = (1,)

tuple

# 7.Define a three-line long string.

In [ ]:
s = """
first line
second line
third line
"""

# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [10]:
t = (1 , 2, 3)
for i in t:
    print(i)

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [13]:
def multy(a, b):
    return a * b
print(multy(3, 5))

15


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [16]:
import numpy as np
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [17]:
import numpy as np
print(np.zeros((4,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [24]:
arr = np.arange(15)
print(arr)
print(arr.reshape(3, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [29]:
m1 = np.mat(np.arange(12).reshape((4,3)))
m2 = np.mat(np.arange(12).reshape((3,4)))
print(m1)
print(m2)
print(np.matmul(m1, m2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]
